language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mallesha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mallesha/docker-react npm run test -- -- coverage
